refactor Synapse API functions to remove nested functions, closes #42

diff --git a/src/synapse/SynapseDeleteRoomStatus b/src/synapse/SynapseDeleteRoomStatus
--- a/src/synapse/SynapseDeleteRoomStatus
+++ b/src/synapse/SynapseDeleteRoomStatus
@@ -6,31 +6,6 @@ SynapseDeleteRoomStatus() {
 
   local job_id="$1"
 
-  DoGetDeleteRoomStatus() {
-    local -A params=(
-      [method]="${s_delete_room_status_api[method]}"
-      [path]="${s_delete_room_status_api[path]}"
-    )
-    local response
-    Request params response || {
-      HandleMatrixError response
-      return 1
-    }
-
-    local -a keys=(status shutdown_room.kicked_users shutdown_room.failed_to_kick_users shutdown_room.local_aliases shutdown_room.new_room_id error)
-    local -A values
-    ProcessResponse response keys values || return 1
-
-    echo -e "\nDeletion job status: ${values[status]}"
-    if [[ "${values[status]}" = "failed" ]]; then
-      echo -e "Error: ${values[error]}"
-    fi
-    echo -e "Kicked users: ${values[shutdown_room.kicked_users]}"
-    echo -e "Failed to kick users: ${values[shutdown_room.failed_to_kick_users]}"
-    echo -e "Local aliases found: ${values[shutdown_room.local_aliases]}"
-    echo -e "New room ID: ${values[shutdown_room.new_room_id]}\n"
-  }
-
   CheckLoginStatus || return 1
   CheckServerSupport "${s_delete_room_status_api[minimum_version]}" || return 1
 
@@ -44,5 +19,27 @@ SynapseDeleteRoomStatus() {
   Log debug "URL 'job_id' param set to '${s_delete_room_status_url_params[job_id]}'"
 
   DefineSynapseEndpoints
-  DoGetDeleteRoomStatus
+
+  local -A params=(
+    [method]="${s_delete_room_status_api[method]}"
+    [path]="${s_delete_room_status_api[path]}"
+  )
+  local response
+  Request params response || {
+    HandleMatrixError response
+    return 1
+  }
+
+  local -a keys=(status shutdown_room.kicked_users shutdown_room.failed_to_kick_users shutdown_room.local_aliases shutdown_room.new_room_id error)
+  local -A values
+  ProcessResponse response keys values || return 1
+
+  echo -e "\nDeletion job status: ${values[status]}"
+  if [[ "${values[status]}" = "failed" ]]; then
+    echo -e "Error: ${values[error]}"
+  fi
+  echo -e "Kicked users: ${values[shutdown_room.kicked_users]}"
+  echo -e "Failed to kick users: ${values[shutdown_room.failed_to_kick_users]}"
+  echo -e "Local aliases found: ${values[shutdown_room.local_aliases]}"
+  echo -e "New room ID: ${values[shutdown_room.new_room_id]}\n"
 }
diff --git a/src/synapse/SynapseDestinationDetails b/src/synapse/SynapseDestinationDetails
--- a/src/synapse/SynapseDestinationDetails
+++ b/src/synapse/SynapseDestinationDetails
@@ -4,35 +4,6 @@
 SynapseDestinationDetails() {
   Log debug "Got args '$*'"
 
-  DoGetDestinationDetails() {
-    local -A params=(
-      [method]="${s_destination_details_api[method]}"
-      [path]="${s_destination_details_api[path]}"
-    )
-    local response
-    Request params response || {
-      HandleMatrixError response
-      return 1
-    }
-
-    local -a keys=(destination retry_last_ts retry_interval failure_ts last_successful_stream_ordering)
-    local -A values
-    ProcessResponse response keys values || return 1
-
-    echo -e "\nDestination: ${values[destination]}"
-    if [[ "${values[failure_ts]}" != "null" ]]; then
-      echo -e "Failed: true"
-      ConvertUnixTimestampMs "values[failure_ts]"
-      echo -e "Failed on: ${values[failure_ts]}"
-      ConvertUnixTimestampMs "values[retry_last_ts]"
-      echo -e "Last retried on: ${values[retry_last_ts]}"
-      echo -e "Retry interval: $(ConvertIntervalMs "${values[retry_interval]}")"
-    else
-      echo -e "Failed: false"
-    fi
-    echo -e "Last stream ordering: ${values[last_successful_stream_ordering]}"
-  }
-
   CheckLoginStatus || return 1
   CheckServerSupport "${s_destination_details_api[minimum_version]}" || return 1
 
@@ -46,5 +17,31 @@ SynapseDestinationDetails() {
     Log debug "URL 'destination' param set to '${s_destination_details_url_params[destination]}'"
 
   DefineSynapseEndpoints
-  DoGetDestinationDetails
+
+  local -A params=(
+    [method]="${s_destination_details_api[method]}"
+    [path]="${s_destination_details_api[path]}"
+  )
+  local response
+  Request params response || {
+    HandleMatrixError response
+    return 1
+  }
+
+  local -a keys=(destination retry_last_ts retry_interval failure_ts last_successful_stream_ordering)
+  local -A values
+  ProcessResponse response keys values || return 1
+
+  echo -e "\nDestination: ${values[destination]}"
+  if [[ "${values[failure_ts]}" != "null" ]]; then
+    echo -e "Failed: true"
+    ConvertUnixTimestampMs "values[failure_ts]"
+    echo -e "Failed on: ${values[failure_ts]}"
+    ConvertUnixTimestampMs "values[retry_last_ts]"
+    echo -e "Last retried on: ${values[retry_last_ts]}"
+    echo -e "Retry interval: $(ConvertIntervalMs "${values[retry_interval]}")"
+  else
+    echo -e "Failed: false"
+  fi
+  echo -e "Last stream ordering: ${values[last_successful_stream_ordering]}"
 }
diff --git a/src/synapse/SynapsePurgeHistoryStatus b/src/synapse/SynapsePurgeHistoryStatus
--- a/src/synapse/SynapsePurgeHistoryStatus
+++ b/src/synapse/SynapsePurgeHistoryStatus
@@ -6,28 +6,6 @@ SynapsePurgeHistoryStatus() {
 
   local job_id="$1"
 
-  DoGetPurgeHistoryStatus() {
-    local -A params=(
-      [method]="${s_purge_history_status_api[method]}"
-      [path]="${s_purge_history_status_api[path]}"
-    )
-    local response
-    Request params response || {
-      HandleMatrixError response
-      return 1
-    }
-
-    local -a keys=(status error)
-    local -A values
-    ProcessResponse response keys values || return 1
-
-    echo -e "Purge job status: ${values[status]}"
-    if [[ "${values[status]}" = "failed" ]]; then
-      echo -e "Error: '${values[error]}'"
-    fi
-    echo
-  }
-
   CheckLoginStatus || return 1
   CheckServerSupport "${s_purge_history_status_api[minimum_version]}" || return 1
 
@@ -41,5 +19,24 @@ SynapsePurgeHistoryStatus() {
   Log debug "URL 'job_id' param set to '${s_purge_history_status_url_params[job_id]}'"
 
   DefineSynapseEndpoints
-  DoGetPurgeHistoryStatus
+
+  local -A params=(
+    [method]="${s_purge_history_status_api[method]}"
+    [path]="${s_purge_history_status_api[path]}"
+  )
+  local response
+  Request params response || {
+    HandleMatrixError response
+    return 1
+  }
+
+  local -a keys=(status error)
+  local -A values
+  ProcessResponse response keys values || return 1
+
+  echo -e "Purge job status: ${values[status]}"
+  if [[ "${values[status]}" = "failed" ]]; then
+    echo -e "Error: '${values[error]}'"
+  fi
+  echo
 }
