feat(util): add "LIST" type to Assert(), emit fatal error for invalid types
close: #69

diff --git a/src/util/Assert b/src/util/Assert
--- a/src/util/Assert
+++ b/src/util/Assert
@@ -35,16 +35,33 @@ Assert() {
         fi
       ;;
     2 ) local variable_name="$1"
-        Log debug "Variable_name is '$variable_name'"
+        Log debug "Variable name is '$variable_name'"
         local value="${!variable_name}"
         Log debug "Value is '$value'"
         local varbase="${variable_name%%\[*]}"
         local type
         GetType "$varbase" type
         Log debug "Type is '$type'"
-        local desired_type="$2"
+        local desired_type="${2^^}" match='false'
         Log debug "Desired type is '$desired_type'"
-        if [[ "$type" == "$desired_type" ]]; then
+        case "$desired_type" in
+          ARRAY|HASH|INT|EXPORT|OTHER)
+            if [[ "$type" == "$desired_type" ]]; then
+             match='true'
+            fi
+          ;;
+          LIST)
+            if [[ "$type" =~ (HASH|ARRAY) ]]; then
+              match='true'
+            fi
+          ;;
+          *)
+           Log fatal "Invalid type '$desired_type'."
+           exit 1
+          ;;
+        esac
+
+        if [[ "$match" == 'true' ]]; then
           Log debug "Types match."
           return 0
         else
