update provided linac

diff --git a/utils/linac b/utils/linac
--- a/utils/linac
+++ b/utils/linac
@@ -1,8 +1,8 @@
 #!/bin/bash
-# shellcheck disable=SC1090
+# shellcheck disable=SC1090,SC2004
 projectName='LINAC'
 projectDescription='LINAC is not a compiler'
-projectVersion=0.7.1
+projectVersion=0.9.1
 projectAuthor='Joe <joe@thisisjoes.site>'
 projectLicense='GPLv3'
 Configure() {
@@ -10,9 +10,12 @@ Configure() {
   config=(
     [config_path]="config"
     [config_file]="linac.conf"
+    [verbosity]="error"
+    [log_level]="info"
+    [log_path]="/tmp"
+    [log_file]="linac.log"
     [src_path]="src/"
     [build_path]="build/"
-    [debug_enabled]="false"
   )
 }
 ReadConfiguration() {
@@ -47,10 +50,66 @@ InitCheck() {
     echo 'Project info not found. Have you initialized a project?' && exit 0;
   fi
 }
-DebugPrint() {
-  if "${config[debug_enabled]}"; then
-    echo "${FUNCNAME[1]} says: $*"
-  fi
+Clean() {
+  local clean_string
+  local dirty_string="$1"
+  local dirty_chars=('!' '@' '#' '$' '%' '^' '&' '\*' '\?' '~' "\'" '\"' "\\" '\/' '(' ')' '[' ']' '{' '}' '<' '>')
+
+  for i in "${dirty_chars[@]}"; do
+    dirty_string="${dirty_string//$i/''}"
+  done
+
+  shopt -s extglob
+
+  dirty_string="${dirty_string//$'\n'/' '}"
+  dirty_string="${dirty_string//[[:space:]]/'_'}"
+  dirty_string="${dirty_string//+(_)/'_'}"
+  dirty_string="${dirty_string/#_/''}"
+  clean_string="${dirty_string/%_/''}"
+
+  echo "$clean_string"
+}
+Log() {
+  LogTerm "$1" "$2"
+  LogFile "$1" "$2"
+}
+LogTerm() {
+  local term_log_type="${1^^}"
+  local term_log_message="$2"
+
+  local verbosity="${config[verbosity]^^}"
+
+  DoLogTerm() {
+    echo "$term_log_type - $term_log_message"
+  }
+
+  case $term_log_type in
+    DEBUG  ) if [[ "$verbosity" = @(DEBUG) ]]; then DoLogTerm; fi;;
+    INFO   ) if [[ "$verbosity" = @(DEBUG|INFO) ]]; then DoLogTerm; fi;;
+    WARN   ) if [[ "$verbosity" = @(DEBUG|INFO|WARN) ]]; then DoLogTerm; fi;;
+    ERROR  ) if [[ "$verbosity" = @(DEBUG|INFO|WARN|ERROR) ]]; then DoLogTerm; fi;;
+    CONFIG ) if [[ "$verbosity" = @(DEBUG|INFO) ]]; then DoLogTerm; fi;;
+    *      ) if [[ "$verbosity" = @(DEBUG) ]]; then DoLogTerm; Log debug "Invalid term log type '$term_log_type' in context '${FUNCNAME[2]}'"; fi;;
+  esac
+}
+LogFile() {
+  local file_log_type="${1^^}"
+  local file_log_message="$2"
+
+  local log_level="${config[log_level]^^}"
+
+  DoLogFile() {
+    echo "[$(date '+%d/%b/%Y:%H:%M:%S.%3N')] ${file_log_type} - ${FUNCNAME[3]}: $file_log_message" >> "${config[log_path]}/${config[log_file]}"
+  }
+
+  case $file_log_type in
+    DEBUG  ) if [[ "$log_level" = @(DEBUG) ]]; then DoLogFile; fi;;
+    INFO   ) if [[ "$log_level" = @(DEBUG|INFO) ]]; then DoLogFile; fi;;
+    WARN   ) if [[ "$log_level" = @(DEBUG|INFO|WARN) ]]; then DoLogFile; fi;;
+    ERROR  ) if [[ "$log_level" = @(DEBUG|INFO|WARN|ERROR) ]]; then DoLogFile; fi;;
+    CONFIG ) if [[ "$log_level" != @(NONE) ]]; then DoLogFile; fi;;
+    *      ) if [[ "$log_level" = @(DEBUG) ]]; then DoLogFile; Log debug "Invalid file log type '$file_log_type' in context '${FUNCNAME[2]}'"; fi;;
+  esac
 }
 ProcessBuildFile() {
   local files
@@ -61,37 +120,76 @@ ProcessBuildFile() {
 }
 BuildProject() {
   local files
-  local target="$1"
   local name="${projectName,,}"
 
+  Log info "Building project '$projectName' from sources in '${config[src_path]}'"
+
   if [ ! -d "${config[build_path]}" ]; then
-    mkdir "${config[build_path]}"
+    Log warn "Configured build path '${config[build_path]}' not found, creating it..."
+    if mkdir -p "${config[build_path]}"; then
+      Log info "Created missing build path '${config[build_path]}'"
+    else
+      Log error "Failed to create missing build path '${config[build_path]}'"
+      return 1
+    fi
   fi
 
-  MakeStub "$target"
-  mapfile -t files < <(ProcessBuildFile "$1")
-  shift
-  arg="$*"
-  arg="${arg#?}"
-  case "$arg" in
-    d )
-      DebugPrint "Debug build enabled."
-      DebugPrint "Args are $*"
-      DebugPrint "Arg is $arg"
-      for ((i=0;i<"${#files[*]}";i++));do
-        find "${files[$i]}" -type f -print0 | xargs -0 cat;
-      done >> "${config[build_path]}""$name"
-      ;;   
+  num_parameters="$#"
+  Log debug "Got '$num_parameters' parameters"
+  case "$num_parameters" in
+    0 ) Log error "No build file given. Use 'linac help' for usage info."
+        return 1
+    ;;
+    1 ) local target="$1"
+    ;;
 
-    * )
-      DebugPrint "Stripped build enabled."
-      DebugPrint "Args are $*"
-      DebugPrint "Arg is $arg"
-      for ((i=0;i<"${#files[*]}";i++));do
-        grep -Ehrv '^\s*\#' "${files[$i]}";
-      done >> "${config[build_path]}""$name"
-      ;;
+    2 ) local option="$1"
+        local target="${*:$#}"
+    ;;
+
+    * ) Log error "Too many parameters passed!"
+        return 1
+    ;;
   esac
+
+  Log debug "Using target '$target'"
+  MakeStub "$target"
+  mapfile -t files < <(ProcessBuildFile "$target")
+  option="${option#?}"
+  Log debug "Option is '$option'"
+  case "$option" in
+    k  ) Log info "Got option '$option', keeping comments."
+         local strip_comments=false
+    ;;
+
+    '' ) Log debug "No option passed, stripping comments."
+         local strip_comments=true
+    ;;
+
+    *  ) Log error "Invalid option '$option' passed."
+         return 1
+    ;;
+  esac
+
+  if [[ "$strip_comments" == true ]]; then
+    for ((i=0;i<"${#files[*]}";i++));do
+      Log info "Building script from source file '${files[$i]}' ($(( $i + 1 ))/${#files[*]})"
+      grep -Ehrv '^\s*\#' -- "${files[$i]}" ||
+        {
+          Log error "Encountered error while building script from source file '${files[$i]}' ($(( $i + 1 ))/${#files[*]})"
+          return 1
+        }
+    done >> "${config[build_path]}""$name"
+  else
+    for ((i=0;i<"${#files[*]}";i++));do
+      Log info "Building script from source file '${files[$i]}' ($(( $i + 1 ))/${#files[*]})"
+      find -- "${files[$i]}" -type f -print0 | xargs -0 cat ||
+        {
+          Log error "Encountered error while building script from source file '${files[$i]}' ($(( $i + 1 ))/${#files[*]})"
+          return 1
+        }
+    done >> "${config[build_path]}""$name"
+  fi
 }
 InitProject() {
   available_licenses=('' 'GPLv3' 'AGPLv3')
@@ -114,15 +212,20 @@ InitProject() {
   }
 
   WriteInitInfo() {
-    echo -e "projectName=$init_name" > "$init_name.info"
-    {
-       echo -e "projectDescription=$init_description"
-       echo -e "projectVersion=0.1.0"
-       echo -e "projectAuthor=$init_author"
-       echo -e "projectLicense=$init_license"
-    } >> "$init_name.info"
+    local project_name
+    project_name="$(Clean "$init_name")"
+    local escaped_description
+    escaped_description="${init_description//\'/\'\\\'\'}"
 
-    echo -e "# Add build files to this file. One per line." > "$init_name.build"
+    echo -e "projectName=$project_name" > "$project_name.info"
+    {
+       echo -e "projectDescription='$escaped_description'"
+       echo -e "projectVersion=0.1.0"
+       echo -e "projectAuthor='$init_author'"
+       echo -e "projectLicense=$init_license"
+    } >> "$project_name.info"
+
+    echo -e "# Add build files to this file. One per line." > "$project_name.build"
   }
 
   local count
@@ -219,12 +322,10 @@ SubCommand() {
        fi
       ;;
     * )
-      Configure
-      ReadConfiguration
-      DebugPrint "Args are $*"
+      Log debug "Args are $*"
       shift
-      DebugPrint "Shifted args"
-      DebugPrint "Args are $*"
+      Log debug "Shifted args"
+      Log debug "Args are $*"
       if ! command -v Sub"${subcommand^}" > /dev/null; then
         echo "Error: '$subcommand' is not a known command."
         echo "       Run 'linac help' for a list of known commands."
@@ -236,8 +337,11 @@ SubCommand() {
   esac
 }
 Main() {
+  PrintInfo
+  Configure
+  ReadConfiguration
   SubCommand "$@"
 }
 
-PrintInfo
+set -o pipefail
 Main "$@"
