chore: update provided LINAC

diff --git a/utils/linac b/utils/linac
--- a/utils/linac
+++ b/utils/linac
@@ -2,7 +2,7 @@
 # shellcheck disable=SC1090,SC2004
 projectName='LINAC'
 projectDescription='LINAC is not a compiler'
-projectVersion=0.9.4
+projectVersion=0.12.2
 projectAuthor='Joe <joe@thisisjoes.site>'
 projectLicense='GPLv3'
 Configure() {
@@ -16,6 +16,7 @@ Configure() {
     [log_file]="linac.log"
     [src_path]="src/"
     [build_path]="build/"
+    [module_path]="modules"
   )
 }
 ReadConfiguration() {
@@ -34,6 +35,7 @@ CreateFiles() {
   if [ ! -d "${config[config_path]}" ]; then
     mkdir "${config[config_path]}"
     mkdir "${config[src_path]}"
+    mkdir "${config[module_path]}"
     mkdir "${config[build_path]}"
     touch "${config[config_path]}"/"${config[config_file]}"
   fi
@@ -111,6 +113,126 @@ LogFile() {
     *      ) if [[ "$log_level" = @(DEBUG) ]]; then DoLogFile; Log debug "Invalid file log type '$file_log_type' in context '${FUNCNAME[2]}'"; fi;;
   esac
 }
+BuildModule() {
+  Log debug "Got args '$*'"
+  local module="$1"
+  local version="$2"
+
+  local module_path="${config[module_path]}"
+  local path="$module_path/${module}/${version}"
+  cd "$path" || {
+      Log error "Failed to enter module directory '$path' for module '$module'"
+      return 1
+  }
+  linac get && linac build -m "${module}.build"
+}
+CheckModuleCache() {
+  local module="$1"
+  local version="$2"
+  local url="$3"
+
+  local module_path="${config[module_path]}"
+
+  if [[ ! -d "$module_path" ]]; then
+    mkdir "$module_path"
+  fi
+
+  if [[ -d "${module_path}/${module}/${version}" ]]; then
+    Log info "Module '$module', version '$version' found in local cache."
+  else
+    Log info "Module '$module', version '$version' not in local cache."
+    return 1
+  fi
+}
+GetModuleDependencies() {
+  local module_file="${projectName,,}.module"
+
+  local -A module_dependencies
+
+  if [[ -f "$module_file" ]]; then
+    . "$module_file" ||
+    {
+      Log error "Failed to load LINAC module file '$module_file'"
+      return 1
+    }
+    Log info "Loaded LINAC module file '$module_file'"
+  else
+    Log info "'${projectName}' has no module file, skipping"
+    return 0
+  fi
+
+  local module
+  for module in "${!module_dependencies[@]}"; do
+    Log debug "$module"
+    Log debug "${module_dependencies[$module]}"
+    declare -A "$module"'='"${module_dependencies[$module]}"
+  done
+
+  for module in "${!module_dependencies[@]}"; do
+    local -n ref
+    ref=${module}
+    local version
+    version="${ref[v]}"
+    local url
+    url="${ref[u]}"
+    CheckModuleCache "$module" "$version" || {
+      RetrieveModule "$module" "$version" "$url"
+    }
+    BuildModule "$module" "$version"
+    unset -n ref
+  done
+}
+GetModulePaths() {
+  local -n __GetModulePaths_paths="$1"
+
+  local module_file="${projectName,,}.module"
+
+  local -A module_dependencies
+
+  if [[ -f "$module_file" ]]; then
+    . "$module_file" ||
+    {
+      Log error "Failed to load LINAC module file '$module_file'"
+      return 1
+    }
+  else
+    Log info "'${projectName}' has no module file, skipping"
+    return 0
+  fi
+
+  local module
+  for module in "${!module_dependencies[@]}"; do
+    Log debug "$module"
+    Log debug "${module_dependencies[$module]}"
+    declare -Ag "$module"'='"${module_dependencies[$module]}"
+  done
+
+  for module in "${!module_dependencies[@]}"; do
+    local -n ref
+    ref=${module}
+    local version
+    version="${ref[v]}"
+    __GetModulePaths_paths+=("${config[module_path]}/${module}/${version}/build/")
+    unset -n ref
+  done
+
+}
+RetrieveModule() {
+  local module="$1"
+  local version="$2"
+  local url="https://$3"
+
+  Log info "Retreiving module '$module' version '$version' from '$url'"
+  if [[ "$version" =~ ^[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}.*$ ]]; then
+    local clone_version="v${version}"
+  else
+    local clone_version="$version"
+  fi
+  git clone -b "$clone_version" --depth 1 "$url" "${config[module_path]}/$module/$version" -c advice.detachedHead=false --quiet >/dev/null || {
+    Log error "Failed to retrieve module '$module' version '$version'. Aborting."
+    exit 1
+  }
+}
 ProcessBuildFile() {
   local files
   mapfile -t files < <(grep -Ev '^\s*#' "$1";)
@@ -153,10 +275,14 @@ BuildProject() {
   esac
 
   Log debug "Using target '$target'"
-  MakeStub "$target"
 
-  local paths
-  mapfile -t paths < <(ProcessBuildFile "$target")
+  local -a paths
+  local -a module_paths
+  GetModulePaths module_paths
+  local -a local_paths
+  mapfile -t local_paths < <(ProcessBuildFile "$target")
+  paths+=("${module_paths[@]}")
+  paths+=("${local_paths[@]}")
   Log debug "Paths are '${paths[*]}'"
 
   local files
@@ -173,6 +299,11 @@ BuildProject() {
          local strip_comments=false
     ;;
 
+    m ) Log info "Got option '$option', building as submodule without stub or entrypoint."
+        local is_submodule=true
+        local strip_comments=true
+    ;;
+
     '' ) Log debug "No option passed, stripping comments."
          local strip_comments=true
     ;;
@@ -181,6 +312,14 @@ BuildProject() {
          return 1
     ;;
   esac
+
+  if [[ ! "$is_submodule" == true ]]; then
+    Log info "Creating stub..."
+    MakeStub
+  else
+    local name="${projectName,,}"
+    [[ -f "${config[build_path]}$name" ]] && rm "${config[build_path]}$name"
+  fi
 
   if [[ "$strip_comments" == true ]]; then
     local args='-Ehrv'
@@ -202,6 +341,11 @@ BuildProject() {
           return 1
         }
     done
+
+  if [[ ! "$is_submodule" == true ]]; then
+    Log info "Appending entrypoint..."
+    AppendEntrypoint
+  fi
 }
 InitProject() {
   available_licenses=('' 'GPLv3' 'AGPLv3')
@@ -221,6 +365,7 @@ InitProject() {
 
     CreateFiles
     WriteInitInfo
+    WriteEntrypoint
   }
 
   WriteInitInfo() {
@@ -272,7 +417,21 @@ MakeStub() {
   if [ -n "${config[shellcheck_ignore]}" ]; then
     echo "# shellcheck disable=${config[shellcheck_ignore]}" >> "${config[build_path]}$name"
   fi
-  cat "$name"'.info' >> "${config[build_path]}$name"
+  echo "$(<"$name"'.info')" >> "${config[build_path]}$name"
+}
+AppendEntrypoint() {
+  printf '\n%s\n' "$(<"${config[src_path]}"'__LINAC_Entrypoint')" >> "${config[build_path]}$name"
+}
+WriteEntrypoint() {
+  {
+    echo '#!/bin/bash'
+    echo '__LINAC_Entrypoint() {'
+    echo '	# All arguments passed to your program are available in this context.'
+    echo "	# Call your program's 'Main' function here, or directly call any"
+    echo '	# other functions.'
+    echo '}'
+    echo '__LINAC_Entrypoint "$@"'
+  } >> "${config[src_path]}__LINAC_Entrypoint"
 }
 PrintInfo() {
   echo -e "${projectName} ${projectVersion}"' - '"${projectDescription}"
@@ -281,6 +440,18 @@ PrintInfo() {
 SubInit() {
   InitProject
 }
+SubFix() {
+  if [[ ! -f "${config[src_path]}__LINAC_Entrypoint" ]]; then
+    Log warn "Default entrypoint does not exist in source path '${config[src_path]}'. Attempting to recreate it..."
+
+    WriteEntrypoint || {
+      Log fatal "Failed to recreate default entrypoint at '${config[src_path]}__LINAC_Entrypoint'."
+      exit 1
+    }
+
+    Log info "Recreated default entrypoint."
+  fi
+}
 SubBump() {
   InitCheck
   BumpVersion "$@"
@@ -288,6 +459,10 @@ SubBump() {
 SubBuild() {
   InitCheck
   BuildProject "$@"
+}
+SubGet() {
+  InitCheck
+  GetModuleDependencies "$@"
 }
 SubHelp() {
     case "$@" in
@@ -303,6 +478,9 @@ SubHelp() {
       "init" )
         echo "  Initializes a new project in the current directory. Starts a wizard which asks for basic information"
         echo "  about your project, then creates the necessary files and directories."
+      ;;
+      "fix" )
+        echo "  Attempts to detect and fix issues with the project."
       ;;
       "help" )
         echo  "  Shows a help message with basic usage information. Takes another command as an option and provides"
@@ -331,6 +509,7 @@ SubCommand() {
          echo "        help [command]           Shows this help. Takes another command as an option."
          echo "        build [build file]       Builds project using the given build file."
          echo "        bump [version]           Bumps the project version. Accepts 'major','minor','patch'."
+         echo "        fix                      Attempts to detect and fix issues with the project in the current directory."
          echo "        init                     Initializes a new project in the current directory."
        fi
       ;;
@@ -357,4 +536,12 @@ Main() {
 }
 
 set -o pipefail
-Main "$@"
+
+#!/bin/bash
+__LINAC_Entrypoint() {
+  # All arguments passed to your program are available in this context.
+  # Call your program's 'Main' function here, or directly call any
+  # other functions.
+  Main "$@"
+}
+__LINAC_Entrypoint "$@"
